### ISSUE TITLE
Communication channel between CPC and AMP infra WG

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/project-onboarding#31]
One of the graduation requirements for AMP from the CPC was to draft a clear plan to disentangle the CDN for the AMP runtime from the Google AMP Cache. This is tracked in https://github.com/ampproject/wg-infra/issues/18.

As there are multiple options and open questions, it's important to establish a communication channel between the CPC and the AMP infra WG, so that there's an upfront consensus as to solutions the CPC will find acceptable.

Just tagging people on the GitHub issue doesn't seem sufficient, please advise how we should proceed.

**Comment by brianwarner** [comment]
Good point, Tobie.  Let's go with a slack channel.  I'll set something up.

**Comment by danielrozenberg** [comment]
We have the #wg-infra channel in the AMP Slack instance, does that work for you?

**Comment by tobie** [comment]
I want to make sure folks on the CPC (which is a much larger group that’s operates on a voluntary basis) get access to this conversation and provide input along the way. The best way to guarantee this is to minimize friction by having that conversation happen on the foundation’s Slack rather than on AMP’s (granted the CPC prefers slack over a mailing list).

**Comment by evenstensberg** [comment]
My take, as mentioned during this week CPC meeting, is that we can have slack to agree on the relevant topic and how we wish to go through with expectations and goals, mainly used for fast-feedback on minor inconveniences or questions and then having a mailing list to discuss, as people are more flexible and efficient when there's a mailing list involved. 

In experience, mailing lists work better for this kind of comms

**Comment by tobie** [comment]
Worth nothing that the whole AMP infra WG will be at the Collab Summit in Montreal. Worth organizing a face to face meeting/session then. /cc @rsimha.

**Comment by mhdawson** [comment]
I'm +1 on the mailing list supplemented by slack.  Also good to take advantage of face to face time in Montreal.

**Comment by tobie** [comment]
Awesome. I'll get an email thread started so folks can share their preferred email for the mailing list and Slack channel invitations.

**Comment by brianwarner** [comment]
Thanks @tobie!  I'll spin up the mailing list.  Anybody who wants to be on the mailing list, send me an email at bwarner@linuxfoundation.org.

**Comment by tobie** [comment]
@brianwarner Thanks! Feel free to close this once folks have been invited to the list.

**Comment by joesepi** [comment]
Made progress at Collab Summit; have issues created and have Slack channel and an email list. @tobie says its cool to close.

Mailing list:
https://lists.openjsf.org/g/amp-onboarding-infrastructure/topics

**Comment by teodora82** [comment]
Nice
