### ISSUE TITLE
Clarify whether the foundation can handle SXG certs

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/project-onboarding#32]
The AMP project needs a [SXG cert](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/signed-exchange/#acquire-a-supported-tls-certificate) on top of its wildcard cert (which can only be obtained via Digicert and _needs to be renewed every 90 days_).

Is this something the foundation is equipped to handle?

**Comment by brianwarner** [comment]
To help plan out the budget, do you have a sense for how much these cost? Is it drastically different from a wildcard cert?

**Comment by tobie** [comment]
@sebastianbenz, can you please advise?

**Comment by sebastianbenz** [comment]
You can find more info about obtaining an SXG cert via Digicert [here](https://www.digicert.com/google-amp-security-solutions/). Afaik, the costs are $55 for each 90 day cert. Note: this is in addition to the wildcard cert.

**Comment by brianwarner** [comment]
Thanks!  That's helpful.  Does the wildcard have to be on the same renewal cadence as the SXG cert?  Or can we do a multi-year wildcard?

**Comment by sebastianbenz** [comment]
multi-year renewal is fine

**Comment by tobie** [comment]
Hey, @brianwarner, could we have an update on this?

**Comment by brianwarner** [comment]
Sorry, I though I responded on this.  Yes, this is fine.
